const RANKS=[
 ["Bronce I",0],["Bronce II",350],["Bronce III",900],
 ["Plata I",1700],["Plata II",2600],["Plata III",3650],
 ["Oro I",4800],["Oro II",6050],["Oro III",7350],
 ["Platino I",8800],["Platino II",10300],["Platino III",11900],
 ["Zafiro I",13600],["Zafiro II",15400],["Zafiro III",17300],["Zafiro IV",19300],
 ["Rubí I",21350],["Rubí II",23450],["Rubí III",25600],["Rubí IV",27800],
 ["Esmeralda I",30050],["Esmeralda II",32350],["Esmeralda III",34700],["Esmeralda IV",37100],
 ["Amatista I",39550],["Amatista II",42050],["Amatista III",44600],["Amatista IV",47200],["Amatista V",49850],
 ["Perla I",52550],["Perla II",55300],["Perla III",58100],["Perla IV",60950],["Perla V",63850],
 ["Obsidiana I",66800],["Obsidiana II",69750],["Obsidiana III",72700],["Obsidiana IV",75750],["Obsidiana V",78800],
 ["Diamante I",81900],["Diamante II",85000],["Diamante III",88100],["Diamante IV",91200],["Diamante V",94200],["Diamante VI",95000],
 ["ULTRA TITAN",100000]
];

const COURSES=[
 {id:"python",name:"Python",icon:"🐍",level:"Principiante",desc:"Aprende programación desde cero: variables, condicionales, bucles, funciones y proyectos.",lessons:[
  {id:"py1",title:"Tu primer programa",text:"Python es un lenguaje de programación sencillo y muy usado. La función print() muestra información en pantalla.",code:'print("Hola, mundo")',q:"¿Qué función muestra texto en Python?",opts:["print()","show()","echo()"],a:0,xp:20},
  {id:"py2",title:"Variables",text:"Una variable guarda un valor para usarlo después. En Python no necesitas declarar el tipo por separado.",code:'nombre = "Ana"\nedad = 20',q:"¿Cuál asignación crea una variable llamada edad?",opts:["edad = 20","20 = edad","var edad 20"],a:0,xp:20},
  {id:"py3",title:"Condicionales",text:"if permite ejecutar código cuando una condición es verdadera. Puedes usar else para el caso contrario.",code:'edad = 18\nif edad >= 18:\n    print("Adulto")',q:"¿Qué palabra inicia un condicional en Python?",opts:["if","when","check"],a:0,xp:25},
  {id:"py4",title:"Bucles",text:"for permite repetir una acción sobre una secuencia o rango.",code:'for i in range(3):\n    print(i)',q:"¿Qué estructura usamos aquí para repetir?",opts:["for","loop","repeat"],a:0,xp:25}
 ]},
 {id:"javascript",name:"JavaScript",icon:"JS",level:"Principiante",desc:"Domina JavaScript para crear páginas interactivas, manejar datos y trabajar con el navegador.",lessons:[
  {id:"js1",title:"Variables con const y let",text:"JavaScript permite declarar variables con let y constantes con const.",code:'const nombre = "Luis";\nlet edad = 18;',q:"¿Cuál palabra se usa para una constante?",opts:["const","fixed","static"],a:0,xp:20},
  {id:"js2",title:"Funciones",text:"Una función agrupa instrucciones reutilizables y puede recibir parámetros.",code:'function sumar(a,b){\n return a+b;\n}',q:"¿Qué palabra declara una función tradicional?",opts:["function","def","func"],a:0,xp:25},
  {id:"js3",title:"DOM y eventos",text:"El DOM representa los elementos HTML. addEventListener permite responder a eventos como clics.",code:'button.addEventListener("click", () => {\n alert("Hola");\n});',q:"¿Qué método escucha un evento?",opts:["addEventListener","listenEvent","onEvent"],a:0,xp:25}
 ]},
 {id:"web",name:"HTML + CSS",icon:"</>",level:"Principiante",desc:"Construye interfaces web: estructura HTML, estilos CSS y diseño responsive.",lessons:[
  {id:"web1",title:"Estructura HTML",text:"HTML define la estructura y el contenido de una página mediante elementos y etiquetas.",code:'<h1>Mi página</h1>\n<p>Hola</p>',q:"¿Qué etiqueta representa el título principal?",opts:["h1","title-text","header1"],a:0,xp:20},
  {id:"web2",title:"Selectores CSS",text:"CSS controla la apariencia. Un selector de clase comienza con un punto.",code:'.boton {\n  padding: 10px;\n}',q:"¿Cómo comienza un selector de clase?",opts:[".","#","@"],a:0,xp:20},
  {id:"web3",title:"Flexbox",text:"Flexbox ayuda a distribuir elementos en una fila o columna de forma flexible.",code:'.menu { display: flex; gap: 10px; }',q:"¿Qué propiedad activa Flexbox?",opts:["display: flex","layout: flex","flex: on"],a:0,xp:25}
 ]},
 {id:"java",name:"Java",icon:"☕",level:"Intermedio",desc:"Programación orientada a objetos, clases, métodos, colecciones y buenas prácticas.",lessons:[
  {id:"java1",title:"Clases y objetos",text:"Una clase define una estructura y un objeto es una instancia de esa clase.",code:'class Persona {\n String nombre;\n}',q:"¿Qué palabra define una clase en Java?",opts:["class","type","object"],a:0,xp:25},
  {id:"java2",title:"Métodos",text:"Los métodos contienen comportamiento que una clase puede ejecutar.",code:'void saludar(){\n System.out.println("Hola");\n}',q:"¿Qué palabra indica que el método no devuelve un valor?",opts:["void","null","empty"],a:0,xp:25}
 ]},
 {id:"cpp",name:"C++",icon:"C++",level:"Intermedio",desc:"Aprende sintaxis, funciones, estructuras y fundamentos de programación de sistemas.",lessons:[
  {id:"cpp1",title:"Variables y tipos",text:"C++ es de tipado estático. Debes indicar el tipo de una variable al declararla.",code:'int edad = 20;\nstring nombre = "Ana";',q:"¿Qué tipo representa un entero?",opts:["int","str","integer"],a:0,xp:25},
  {id:"cpp2",title:"Funciones",text:"Las funciones permiten organizar y reutilizar código.",code:'int sumar(int a,int b){ return a+b; }',q:"¿Qué devuelve esta función?",opts:["Un entero","Un texto","Nada"],a:0,xp:25}
 ]}
];

const KEY="codemaster_pro_v6";
const OLD_KEYS=["codemaster_pro_v2"];
function loadDB(){
 try{
  const saved=localStorage.getItem(KEY);
  if(saved)return JSON.parse(saved);
  for(const oldKey of OLD_KEYS){const old=localStorage.getItem(oldKey);if(old){const parsed=JSON.parse(old);localStorage.setItem(KEY,JSON.stringify(parsed));return parsed;}}
 }catch(e){}
 return {users:{},session:null};
}
let db=loadDB();
if(!db.users)db.users={};

function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function user(){return db.session?db.users[db.session]:null}
function currentRank(xp){let i=0;for(let n=0;n<RANKS.length;n++)if(xp>=RANKS[n][1])i=n;return i}
function rankMeta(xp){const i=currentRank(xp),r=RANKS[i],next=RANKS[Math.min(RANKS.length-1,i+1)];return {i,r,next,isMax:i===RANKS.length-1}}
function rankIcon(i){const n=RANKS[i][0];if(n.startsWith("Bronce"))return "🥉";if(n.startsWith("Plata"))return "🥈";if(n.startsWith("Oro"))return "🥇";if(n.startsWith("Platino"))return "🔷";if(n.startsWith("Zafiro"))return "💠";if(n.startsWith("Rubí"))return "♦️";if(n.startsWith("Esmeralda"))return "💚";if(n.startsWith("Amatista"))return "🔮";if(n.startsWith("Perla"))return "⚪";if(n.startsWith("Obsidiana"))return "⬛";if(n.startsWith("Diamante"))return "💎";return "👑"}
function rankClass(i){const n=RANKS[i][0];return n==="ULTRA TITAN"?"ultra":n.split(" ")[0].toLowerCase().replace("í","i")}
function rankBadge(xp,large=false){const m=rankMeta(xp);return `<span class="rank-badge ${rankClass(m.i)} ${large?"large":""}"><span>${rankIcon(m.i)}</span><strong>${esc(m.r[0])}</strong></span>`}
function weekKey(d=new Date()){const x=new Date(d);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x.toISOString().slice(0,10)}
function ensureWeek(u){const k=weekKey();if(u.weekKey!==k){u.weekXp=0;u.weekKey=k;save()}}
function completedCount(u){return Object.values(u.progress||{}).filter(Boolean).length}
function totalLessons(){return COURSES.reduce((n,c)=>n+c.lessons.length,0)}
function toast(msg){const t=document.createElement("div");t.className="toast";t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
function avatarMarkup(u,cls="avatar"){return u.avatar?`<img class="${cls} avatar-photo" src="${u.avatar}" alt="Foto de perfil">`:`<div class="${cls}">${esc((u.name||"CM").slice(0,2).toUpperCase())}</div>`}
function migrateUser(u){u.xp=Number(u.xp)||0;u.weekXp=Number(u.weekXp)||0;u.progress=u.progress||{};u.selectedLanguage=u.selectedLanguage||"";u.onboardingDone=!!u.onboardingDone;u.streak=Number(u.streak)||0;u.lastStudy=u.lastStudy||null;u.avatar=u.avatar||"";return u}
Object.values(db.users).forEach(migrateUser);save();

function render(){
 if(!db.session){renderAuth();return}
 const u=user();if(!u){db.session=null;save();renderAuth();return}
 migrateUser(u);ensureWeek(u);
 if(!u.onboardingDone){renderOnboarding(1);return}
 renderShell("inicio");home();
}

function renderOnboarding(step=1){
 const u=user(),selected=u.selectedLanguage||"",progress=Math.min(100,step/3*100);
 document.getElementById("app").innerHTML=`<div class="onboarding"><div class="onboarding-top"><div class="logo"><span class="logo-mark">&lt;/&gt;</span><span>CodeMaster</span></div><div class="onboarding-step">Paso ${step} de 3</div></div><div class="onboarding-progress"><i style="width:${progress}%"></i></div><div class="onboarding-body">
 ${step===1?`<section class="onboarding-card welcome-step"><div class="welcome-copy"><span class="badge">BIENVENIDO A CODEMASTER</span><h1>Aprende a programar de forma <span>práctica y divertida.</span></h1><p>Hola, ${esc(u.name||"programador")}. Soy <strong>Byte</strong>, tu compañero de aprendizaje. Te acompaño desde tu primera línea de código hasta <strong>ULTRA TITAN</strong>.</p><div class="onboarding-points"><div><b>📚 Lecciones</b><small>Aprende un concepto y practica.</small></div><div><b>⚡ XP</b><small>Gana experiencia al completar ejercicios.</small></div><div><b>🔥 Racha</b><small>Convierte el aprendizaje en un hábito.</small></div></div><button class="primary big-btn" id="nextOnboarding">Comenzar mi ruta →</button></div><div class="mascot-panel animated-mascot" id="onboardMascot"><div class="mascot-glow"></div><span class="bubble b1">+XP</span><span class="bubble b2">🔥</span><span class="bubble b3">&lt;/&gt;</span><img src="shark.png" alt="Byte, mascota de CodeMaster"><div class="mascot-caption"><strong>¡Soy Byte! 🦈</strong><span>Tu guía para aprender programación.</span></div></div></section>`:
 step===2?`<section class="onboarding-card language-step"><div class="center-heading"><span class="badge">PASO 1 · ELIGE TU RUTA</span><h1>¿Qué lenguaje quieres aprender?</h1><p>Tu elección será la ruta principal de tu inicio. Después podrás explorar todos los cursos.</p></div><div class="language-grid">${COURSES.map(c=>`<button class="language-option ${selected===c.id?"selected":""}" data-language="${c.id}"><span class="language-icon">${c.icon}</span><span><strong>${c.name}</strong><small>${c.level} · ${c.lessons.length} lecciones</small></span><span class="check">✓</span></button>`).join("")}</div><div class="onboarding-actions"><button class="secondary" id="backOnboarding">← Atrás</button><button class="primary big-btn" id="continueLanguage" ${selected?"":"disabled"}>Continuar →</button></div></section>`:
 `<section class="onboarding-card methodology-step"><div class="center-heading"><span class="badge">PASO 2 · TU METODOLOGÍA</span><h1>Sube de rango aprendiendo</h1><p>Empiezas en <strong>Bronce I</strong> y recorres ${RANKS.length} rangos hasta <strong>ULTRA TITAN</strong>.</p></div><div class="method-grid"><div class="method-card"><div class="method-icon">🥉</div><strong>Inicio</strong><p>Todos empiezan en <b>Bronce I</b> con 0 XP.</p></div><div class="method-card"><div class="method-icon">⚡</div><strong>XP por aprendizaje</strong><p>La XP se obtiene al responder correctamente y completar una lección.</p></div><div class="method-card"><div class="method-icon">🏆</div><strong>Meta final</strong><p><b>ULTRA TITAN</b> es el rango máximo y se alcanza con <b>100.000 XP</b>.</p></div></div><div class="rank-road"><div class="road-title"><strong>Ruta de rangos</strong><span>46 rangos · 0 → 100.000 XP</span></div><div class="road-track">${RANKS.map((x,i)=>`<div class="road-node ${i===RANKS.length-1?"ultra":i===0?"start":""}"><span>${rankIcon(i)}</span><strong>${x[0]}</strong><small>${x[1].toLocaleString("es-CO")} XP</small></div>`).join("")}</div></div><div class="streak-box"><div class="streak-fire">🔥</div><div><strong>Racha de aprendizaje</strong><p>Completa al menos una lección al día. Los días consecutivos aumentan tu racha; si rompes la continuidad, tu nueva racha comienza en 1.</p></div></div><div class="xp-rule"><span>🛡️</span><div><strong>Progreso seguro</strong><p>Ningún botón de navegación entrega XP. Cada lección solo puede recompensarse una vez.</p></div></div><div class="onboarding-actions"><button class="secondary" id="backMethodology">← Atrás</button><button class="primary big-btn" id="finishOnboarding">Entrar a CodeMaster 🚀</button></div></section>`}
 </div></div>`;
 if(step===1){document.getElementById("nextOnboarding").onclick=()=>renderOnboarding(2);document.getElementById("onboardMascot").onclick=()=>mascotCelebrate()}
 if(step===2){document.querySelectorAll("[data-language]").forEach(b=>b.onclick=()=>{u.selectedLanguage=b.dataset.language;save();renderOnboarding(2)});document.getElementById("backOnboarding").onclick=()=>renderOnboarding(1);document.getElementById("continueLanguage").onclick=()=>{if(u.selectedLanguage)renderOnboarding(3)}}
 if(step===3){document.getElementById("backMethodology").onclick=()=>renderOnboarding(2);document.getElementById("finishOnboarding").onclick=()=>{u.onboardingDone=true;save();render();toast("¡Ruta configurada! Bienvenido a CodeMaster 🦈")}}
}

function renderAuth(mode="login"){
 document.getElementById("app").innerHTML=`<div class="auth"><div class="auth-card"><div class="logo"><span class="logo-mark">&lt;/&gt;</span><span>CodeMaster</span></div><h1>${mode==="login"?"Bienvenido de nuevo":"Crea tu cuenta"}</h1><p>${mode==="login"?"Continúa tu aprendizaje y conserva tu progreso.":"Empieza tu ruta para convertirte en programador."}</p><form class="form" id="authForm">${mode==="register"?`<div class="field"><label>Nombre</label><input id="name" required minlength="2" placeholder="Tu nombre"></div>`:""}<div class="field"><label>Correo</label><input id="email" type="email" required placeholder="tu@email.com"></div><div class="field"><label>Contraseña</label><input id="password" type="password" required minlength="6" placeholder="Mínimo 6 caracteres"></div><div class="error" id="authError"></div><button class="primary">${mode==="login"?"Iniciar sesión":"Crear cuenta"}</button></form><p style="text-align:center;margin-top:18px">${mode==="login"?"¿No tienes cuenta?":"¿Ya tienes cuenta?"} <button class="link" id="switchAuth">${mode==="login"?"Crear una":"Iniciar sesión"}</button></p><p style="font-size:11px;text-align:center">Demo local: las cuentas y fotos se guardan en este navegador. Para cuentas reales entre dispositivos hace falta una base de datos.</p></div></div>`;
 document.getElementById("switchAuth").onclick=()=>renderAuth(mode==="login"?"register":"login");
 document.getElementById("authForm").onsubmit=e=>{e.preventDefault();const email=document.getElementById("email").value.trim().toLowerCase(),pass=document.getElementById("password").value,err=document.getElementById("authError");if(mode==="register"){if(db.users[email]){err.textContent="Ese correo ya está registrado.";return}db.users[email]={email,name:document.getElementById("name").value.trim(),password:pass,xp:0,weekXp:0,weekKey:weekKey(),streak:0,lastStudy:null,progress:{},selectedLanguage:"",onboardingDone:false,avatar:"",created:new Date().toISOString()};db.session=email;save();render();toast("Cuenta creada. ¡Bienvenido!")}else{if(!db.users[email]||db.users[email].password!==pass){err.textContent="Correo o contraseña incorrectos.";return}db.session=email;save();render()}};
}

function renderShell(active){
 const u=user(),m=rankMeta(u.xp);
 document.getElementById("app").innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><div class="logo"><span class="logo-mark">&lt;/&gt;</span><span class="brand-name">CodeMaster</span></div></div><div class="nav-title">APRENDER</div><div class="nav">${nav("inicio","🏠","Inicio",active)}${nav("cursos","📚","Mi ruta",active)}${nav("retos","⚔️","Retos",active)}${nav("misiones","🎯","Misiones",active)}${nav("logros","🏆","Logros",active)}${nav("stats","📊","Progreso",active)}${nav("ranking","🏅","Ranking",active)}${nav("perfil","👤","Perfil",active)}</div><div class="sidebar-mascot animated-mascot" id="sidebarMascot"><div class="mascot-mini"><img src="shark.png" alt="Byte"></div><div><strong>Byte</strong><span>¡Sigue programando!</span></div></div><div class="side-bottom"><button class="nav" id="logout">🚪 <span>Cerrar sesión</span></button></div></aside><main class="main"><header class="topbar"><div><small>PLATAFORMA DE APRENDIZAJE</small><h1 id="title">Dashboard</h1></div><div class="user"><div class="header-rank">${rankBadge(u.xp)}<small>${u.xp.toLocaleString("es-CO")} XP</small></div><button class="user-button" id="openProfile" title="Abrir perfil">${avatarMarkup(u,"avatar")}</button></div></header><div class="content" id="content"></div></main></div>`;
 document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>{const v=b.dataset.nav;renderShell(v);pages[v]()});
 document.getElementById("logout").onclick=()=>{db.session=null;save();renderAuth()};
 document.getElementById("openProfile").onclick=()=>{renderShell("perfil");profile()};
 document.getElementById("sidebarMascot").onclick=()=>mascotCelebrate();
}
function nav(id,icon,label,active){return `<button class="${active===id?"active":""}" data-nav="${id}">${icon} <span>${label}</span></button>`}
const pages={inicio:home,cursos:courses,retos:challenges,misiones:missions,logros:achievements,stats:stats,ranking:ranking,perfil:profile};

function home(){
 const u=user(),m=rankMeta(u.xp),selected=COURSES.find(c=>c.id===u.selectedLanguage)||COURSES[0],pct=m.isMax?100:Math.min(100,((u.xp-m.r[1])/(m.next[1]-m.r[1]))*100);
 document.getElementById("title").textContent="Inicio";
 document.getElementById("content").innerHTML=`<div class="welcome-hero"><div class="welcome-main"><span class="badge">TU RUTA DE APRENDIZAJE</span><h2>Hola, ${esc(u.name)} 👋</h2><p>Continúa con <strong>${selected.name}</strong> y sigue avanzando por tu ruta.</p><div class="current-rank-display">${rankBadge(u.xp,true)}<span>${m.isMax?"Has alcanzado el rango máximo.":`${Math.max(0,m.next[1]-u.xp).toLocaleString("es-CO")} XP para ${esc(m.next[0])}`}</span></div><div class="rank-progress"><div class="rank-progress-head"><strong>${m.r[0]}</strong><span>${u.xp.toLocaleString("es-CO")} / ${m.isMax?"100.000":m.next[1].toLocaleString("es-CO")} XP</span></div><div class="bar"><i style="width:${pct}%"></i></div></div><button class="primary big-btn" id="continueRoute">Continuar aprendiendo →</button></div><div class="hero-mascot animated-mascot" id="homeMascot"><div class="mascot-glow"></div><span class="bubble b1">+XP</span><span class="bubble b2">🔥</span><span class="bubble b3">🏆</span><img src="shark.png" alt="Byte"><div class="speech"><strong>¡Vamos, ${esc(u.name)}!</strong><span>Una lección más y seguimos avanzando. 🦈</span></div></div></div><div class="grid g4 stat-row">${stat("⚡",u.xp.toLocaleString("es-CO"),"XP total")}${stat("📅",u.weekXp.toLocaleString("es-CO"),"XP esta semana")}${stat("🔥",u.streak+" días","Racha")}${stat("🏅",m.r[0],"Rango actual")}</div><div class="rank-highlight"><div><span class="eyebrow">TU INSIGNIA ACTUAL</span><h3>${rankIcon(m.i)} ${esc(m.r[0])}</h3><p>Estás en el rango ${m.i+1} de ${RANKS.length}. El objetivo final es <strong>ULTRA TITAN · 100.000 XP</strong>.</p></div>${rankBadge(u.xp,true)}<button class="secondary" id="seeRanking">Ver tabla de ranking</button></div><div class="section section-head"><div><h2>Tu camino</h2><span class="muted">Avanza lección por lección</span></div><button class="secondary" id="seeAllCourses">Ver cursos</button></div><div class="learning-path">${selected.lessons.map((l,i)=>{const done=!!u.progress[l.id],locked=i>0&&!u.progress[selected.lessons[i-1].id];return `<div class="path-step ${done?"done":""} ${locked?"locked":""}"><div class="path-line"></div><button class="path-node" data-path-lesson="${l.id}" ${locked?"disabled":""}>${done?"✓":locked?"🔒":i+1}</button><div class="path-card"><span class="badge">${done?"COMPLETADA":locked?"BLOQUEADA":"SIGUIENTE"}</span><h3>${l.title}</h3><p>${l.text}</p><div><span class="xp">+${l.xp} XP</span>${done?" · ✓ completada":""}</div></div></div>`}).join("")}</div>`;
 document.getElementById("continueRoute").onclick=()=>{const first=selected.lessons.find(l=>!u.progress[l.id]);openLesson(selected.id,first?first.id:selected.lessons[0].id)};
 document.getElementById("seeAllCourses").onclick=()=>{renderShell("cursos");courses()};document.getElementById("seeRanking").onclick=()=>{renderShell("ranking");ranking()};document.getElementById("homeMascot").onclick=()=>mascotCelebrate();document.querySelectorAll("[data-path-lesson]").forEach(b=>b.onclick=()=>openLesson(selected.id,b.dataset.pathLesson));
}
function stat(icon,val,label){return `<div class="card"><div class="stat-icon">${icon}</div><div class="value">${val}</div><div class="label">${label}</div></div>`}
function courseCard(c){const u=user(),done=c.lessons.filter(l=>u.progress[l.id]).length;return `<div class="card course"><div class="course-top"><div class="course-icon">${c.icon}</div><div><h3>${c.name}</h3><span class="badge">${c.level}</span><p style="margin-top:8px">${c.desc}</p></div></div><div><div class="label">${done}/${c.lessons.length} lecciones</div><div class="bar" style="margin:7px 0;background:#e7e9f0"><i style="width:${done/c.lessons.length*100}%;background:var(--green)"></i></div><button class="primary" data-course="${c.id}">${done?"Continuar":"Comenzar"}</button></div></div>`}
function courses(){document.getElementById("title").textContent="Mi ruta";document.getElementById("content").innerHTML=`<div class="section"><div><h2>Elige tu ruta</h2><span class="muted">Aprende a tu ritmo · ${COURSES.length} cursos disponibles</span></div></div><div class="grid g3">${COURSES.map(courseCard).join("")}</div>`;document.querySelectorAll("[data-course]").forEach(b=>b.onclick=()=>openCourse(b.dataset.course))}
function openCourse(id){const c=COURSES.find(x=>x.id===id);if(!c)return;renderShell("cursos");document.getElementById("title").textContent=c.name;document.getElementById("content").innerHTML=`<div class="card"><span class="badge">${c.level}</span><h2>${c.icon} ${c.name}</h2><p class="muted">${c.desc}</p></div><div class="section"><h2>Ruta del curso</h2><span class="muted">${c.lessons.length} lecciones · XP solo al completar</span></div><div class="path">${c.lessons.map((l,i)=>{const done=user().progress[l.id];return `<div class="card lesson ${done?"done":""}"><div class="lesson-info"><div class="lesson-num">${done?"✓":i+1}</div><div><strong>${l.title}</strong><div class="muted">${done?"Completada":"Lección interactiva"} · <span class="xp">+${l.xp} XP</span></div></div></div><button class="${done?"secondary":"primary"}" data-lesson="${l.id}">${done?"Repasar":"Aprender"}</button></div>`}).join("")}</div>`;document.querySelectorAll("[data-lesson]").forEach(b=>b.onclick=()=>openLesson(c.id,b.dataset.lesson))}
function openLesson(cid,lid){const c=COURSES.find(x=>x.id===cid),l=c?.lessons.find(x=>x.id===lid),u=user();if(!c||!l)return;const done=!!u.progress[l.id];renderShell("cursos");document.getElementById("title").textContent=l.title;document.getElementById("content").innerHTML=`<button class="secondary" id="back">← Volver al curso</button><div class="card lesson-card" style="margin-top:15px"><div class="lesson-mascot"><img src="shark.png" alt="Byte"><div><span class="badge">${c.name}</span><h2>${l.title}</h2><p>Byte te acompaña en esta lección. Lee el concepto, responde y gana XP.</p></div></div><p style="line-height:1.7">${l.text}</p><pre class="code-block">${esc(l.code)}</pre><div class="exercise"><strong>Ejercicio de comprensión</strong><p>${l.q}</p><div class="answer">${l.opts.map((o,i)=>`<button data-answer="${i}">${esc(o)}</button>`).join("")}</div><div id="feedback" class="feedback" style="margin-top:12px"></div></div><div class="complete"><span>${done?'<span class="xp">✓ Lección completada · XP ya reclamada</span>':`Recompensa: <strong class="xp">+${l.xp} XP</strong>`}</span><button class="primary" id="finish" ${done?"disabled":""}>${done?"Completada":"Completar lección"}</button></div></div>`;document.getElementById("back").onclick=()=>openCourse(cid);let correct=false;document.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>{const n=+b.dataset.answer;document.querySelectorAll("[data-answer]").forEach(x=>x.classList.remove("correct","wrong"));b.classList.add(n===l.a?"correct":"wrong");correct=n===l.a;document.getElementById("feedback").innerHTML=correct?"<strong>¡Correcto! 🎉</strong> Ya puedes completar la lección.":"<strong>Inténtalo de nuevo.</strong> Revisa la explicación y vuelve a responder.";if(correct)mascotCelebrate()});document.getElementById("finish").onclick=()=>{if(done)return;if(!correct){document.getElementById("feedback").textContent="Responde correctamente el ejercicio antes de completar la lección.";return}const before=rankMeta(u.xp).i;u.progress[l.id]=true;u.xp+=l.xp;u.weekXp+=l.xp;updateStreak(u);save();const after=rankMeta(u.xp).i;toast(`+${l.xp} XP · Lección completada`);if(after>before)toast(`🏆 ¡Subiste a ${RANKS[after][0]}!`);openLesson(cid,lid)}}
function updateStreak(u){const today=new Date().toISOString().slice(0,10);if(u.lastStudy===today)return;if(u.lastStudy){const a=new Date(u.lastStudy),b=new Date(today),days=Math.round((b-a)/86400000);u.streak=days===1?u.streak+1:1}else u.streak=1;u.lastStudy=today}
function challenges(){const items=[["⚔️","Desafío de variables","Completa una lección de variables para desbloquear este reto."],["🧩","Desafío de lógica","Resuelve ejercicios dentro de las lecciones."],["🔥","Reto de racha","Estudia al menos una lección hoy."]];document.getElementById("content").innerHTML=`<div class="grid g3">${items.map(x=>`<div class="card"><div style="font-size:30px">${x[0]}</div><h3>${x[1]}</h3><p class="muted">${x[2]}</p><button class="secondary" data-go="cursos">Ir a estudiar</button></div>`).join("")}</div>`;document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{renderShell("cursos");courses()})}
function missions(){const u=user(),today=new Date().toISOString().slice(0,10);document.getElementById("content").innerHTML=`<div class="grid g3"><div class="card"><h3>🎯 Primera lección del día</h3><p class="muted">Completa una lección y conserva tu racha.</p><span class="xp">+20 XP o más</span><br><button class="primary" style="margin-top:15px" id="study">Estudiar</button></div><div class="card"><h3>📅 Progreso semanal</h3><p class="muted">Acumula XP aprendiendo durante la semana.</p><strong>${u.weekXp.toLocaleString("es-CO")} XP</strong><div class="bar" style="margin-top:9px;background:#e7e9f0"><i style="width:${Math.min(100,u.weekXp)}%;background:var(--primary)"></i></div></div><div class="card"><h3>🔥 Racha</h3><p class="muted">Una lección completada cuenta como actividad del día.</p><strong>${u.streak} días</strong>${u.lastStudy===today?'<span class="success-text"> · Activa hoy</span>':''}</div></div><div class="card" style="margin-top:18px"><strong>Regla de XP</strong><p class="muted">No existen botones que den XP por sí solos. La XP se entrega únicamente cuando respondes correctamente y completas una lección que todavía no habías completado.</p></div>`;document.getElementById("study").onclick=()=>{renderShell("cursos");courses()}}
function achievements(){const u=user(),items=[["🏆","Primer paso",completedCount(u)>=1],["⚡","100 XP",u.xp>=100],["📚","5 lecciones",completedCount(u)>=5],["🔥","Racha de 7 días",u.streak>=7],["💎","500 XP",u.xp>=500],["👑","1.000 XP",u.xp>=1000],["🌌","10.000 XP",u.xp>=10000],["👑","ULTRA TITAN",u.xp>=100000]];document.getElementById("title").textContent="Logros";document.getElementById("content").innerHTML=`<div class="grid g3">${items.map(x=>`<div class="card achievement ${x[2]?"unlocked":""}"><div style="font-size:34px">${x[2]?x[0]:"🔒"}</div><h3>${x[1]}</h3><p class="muted">${x[2]?"Desbloqueado":"Sigue aprendiendo para desbloquearlo."}</p></div>`).join("")}</div>`}
function stats(){const u=user(),m=rankMeta(u.xp);document.getElementById("title").textContent="Progreso";document.getElementById("content").innerHTML=`<div class="grid g3">${stat("⚡",u.xp.toLocaleString("es-CO"),"XP total")}${stat("📅",u.weekXp.toLocaleString("es-CO"),"XP semanal")}${stat("📚",completedCount(u),"Lecciones completadas")}</div><div class="card current-rank-card"><div><span class="eyebrow">RANGO ACTUAL</span><h2>${rankIcon(m.i)} ${esc(m.r[0])}</h2><p class="muted">Rango ${m.i+1} de ${RANKS.length}</p></div>${rankBadge(u.xp,true)}<div class="rank-big-progress"><div class="rank-progress-head"><span>${u.xp.toLocaleString("es-CO")} XP</span><span>${m.isMax?"100.000 XP · Máximo":`${m.next[1].toLocaleString("es-CO")} XP · ${esc(m.next[0])}`}</span></div><div class="bar"><i style="width:${m.isMax?100:Math.min(100,((u.xp-m.r[1])/(m.next[1]-m.r[1]))*100)}%"></i></div></div></div><div class="section"><h2>Todos los rangos</h2><span class="muted">Cada rango tiene una insignia y un umbral de XP.</span></div><div class="rank-list">${RANKS.map((x,i)=>`<div class="rank-item ${i===m.i?"current":""} ${i===RANKS.length-1?"ultra-row":""}"><div class="rank-left"><span class="rank-mini">${rankIcon(i)}</span><strong>${i+1}. ${x[0]}</strong></div><small>${x[1].toLocaleString("es-CO")} XP${i===m.i?" · Actual":""}</small></div>`).join("")}</div>`}
function leaderboardRow(u,i,me){const isMe=u.email===me.email;return `<div class="table-row ${isMe?"me":""}"><div class="position">${i===0?"👑":i+1}</div><div class="player">${avatarMarkup(u,"table-avatar")}<div><strong>${esc(u.name||"Programador")} ${isMe?'<span class="you-tag">TÚ</span>':""}</strong><small>${esc(u.email||"")}</small></div></div><div>${rankBadge(u.xp)}</div><div><strong>${u.xp.toLocaleString("es-CO")}</strong> XP</div><div>🔥 ${u.streak||0} días</div></div>`}
function ranking(){const entries=Object.values(db.users).map(u=>migrateUser(u)).sort((a,b)=>b.xp-a.xp||String(a.name||"").localeCompare(String(b.name||""),"es"));const me=user();document.getElementById("title").textContent="Ranking";const rows=entries.length?entries.map((u,i)=>leaderboardRow(u,i,me)).join(""): '<div class="empty-state">Todavía no hay cuentas para mostrar.</div>';document.getElementById("content").innerHTML=`<div class="ranking-hero"><div><span class="badge">TABLA DE RANKING</span><h2>Compara tu progreso</h2><p>La tabla ordena las cuentas guardadas en este navegador por XP total.</p></div><img src="shark.png" alt="Byte"></div><div class="card table-card"><div class="table-head"><div>Posición</div><div>Programador</div><div>Rango</div><div>XP</div><div>Racha</div></div>${rows}</div><div class="ranking-note">💡 En esta versión local, el ranking se comparte entre las cuentas creadas en el mismo navegador. Un ranking mundial requerirá un servidor y base de datos.</div>`}

function profile(){const u=user(),m=rankMeta(u.xp);document.getElementById("title").textContent="Mi perfil";document.getElementById("content").innerHTML=`<div class="profile-grid"><section class="card profile-card"><div class="profile-cover"><div class="profile-avatar-wrap">${avatarMarkup(u,"profile-avatar")}</div></div><div class="profile-body"><h2>${esc(u.name)}</h2><p class="muted">${esc(u.email)}</p><div class="profile-rank">${rankBadge(u.xp,true)}<span>${u.xp.toLocaleString("es-CO")} XP</span></div><div class="profile-actions"><label class="primary upload-btn">📷 Cambiar foto<input id="avatarInput" type="file" accept="image/png,image/jpeg,image/webp" hidden></label><button class="secondary" id="removeAvatar" ${u.avatar?"":"disabled"}>Eliminar foto</button></div><p class="help-text">Puedes subir JPG, PNG o WEBP. La imagen se ajusta automáticamente para mantener tu perfil ligero.</p></div></section><section class="card profile-stats"><div class="section-title"><h2>Tu resumen</h2><span class="muted">Tu progreso en CodeMaster</span></div><div class="profile-stat"><span>🏅 Rango</span><strong>${esc(m.r[0])}</strong></div><div class="profile-stat"><span>⚡ XP total</span><strong>${u.xp.toLocaleString("es-CO")}</strong></div><div class="profile-stat"><span>🔥 Racha</span><strong>${u.streak} días</strong></div><div class="profile-stat"><span>📚 Lecciones</span><strong>${completedCount(u)}/${totalLessons()}</strong></div><div class="profile-stat"><span>🎯 Objetivo final</span><strong>100.000 XP</strong></div><button class="secondary full" id="changeLanguage">Cambiar lenguaje principal</button></section></div>`;document.getElementById("avatarInput").onchange=e=>{const file=e.target.files?.[0];if(file)resizeAvatar(file).then(data=>{u.avatar=data;save();profile();toast("Foto de perfil actualizada 📷")}).catch(()=>toast("No se pudo procesar la imagen."))};document.getElementById("removeAvatar").onclick=()=>{if(!u.avatar)return;u.avatar="";save();profile();toast("Foto de perfil eliminada")};document.getElementById("changeLanguage").onclick=()=>{renderOnboarding(2)}}
function resizeAvatar(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith("image/"))return reject();const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=320,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext("2d");ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.84))};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}
function mascotCelebrate(){document.querySelectorAll(".animated-mascot").forEach(el=>{el.classList.remove("celebrate");void el.offsetWidth;el.classList.add("celebrate")});toast("🦈 ¡Byte está listo para la próxima misión!")}

render();
